### ISSUE TITLE
1.7 pls

### ISSUE THREAD

**Issue by AlfieC** [Matsv/PAaaS#6]
title as follows
making a 1.9 -> 1.7 protocol hack but my tables of differences are too big to maintain manually :[

**Comment by MylesIsCool** [comment]
Unless you wish to add support yourself there is no plans for us to add this.

AFAIK, it's just making burger possibly use an older version, unsure.

**Comment by Pokechu22** [comment]
Burger kinda works with 1.7.10, but some of the toppings don't work.  It _looks_ like the `packetinstructions` topping works, though, so you should be able to just tell it to only generate `packetinstructions`.  Except that looks like what's already being done - so I'm not sure why it's not working.

It seems like the blocks topping is the broken one, which breaks a few other toppings (items and recipes depend upon it).  But the toppings PAaaS uses are fine...

**Comment by Pokechu22** [comment]
OK, I checked - 1.7 support isn't there for all versions (packets fails on a few and I'm getting JSON format errors for others), but it _does_ work for 1.7.10 and a few of the versions before it (but not all of the 1.7.x versions).  It probably would be best to add support for 1.7.10 by changing the date used for comparison to `1400088563000L`, since that seems to work well enough.  I'll try to figure out what's wrong with burger.

It does seem like `version` doesn't work on 1.7.10 annoyingly.  But the packets list is there, so that's probably good enough for the moment for PAaaS.
